# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WC5fYOzaQ2C_iqmWDDTzHzEYywLQLFKw
"""

# No loops! All vectorized code.

def getBondPrice(y, face, couponRate, m, ppy=1):
 m = 10
 import numpy as np
 years = np.arange(1,m+1)
 years
 df = 1/(1+.03)
 dfs = df ** years
 dfs

 cf = dfs * .04 * 2000000
 price = sum(cf) + dfs[-1] * 2000000
 price
 return (price)

# Test values
y = 0.03
face = 2000000
couponRate = 0.04
m = 10
getBondPrice(y, face, couponRate, m, ppy=1)