# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WC5fYOzaQ2C_iqmWDDTzHzEYywLQLFKw
"""

# No loops! All vectorized code.

import numpy as np

def getBondPrice(y, face, couponRate, m, ppy=1):
 years = np.arange(1, m * ppy + 1)
 df = 1 / (1 + y / ppy)
 dfs = df ** years
 cf = dfs * couponRate / ppy * face
 price = sum(cf) + dfs[-1] * face

 return (price)

# Test values
y = 0.03
face = 2000000
couponRate = 0.04
m = 10
ppy = 2

price=getBondPrice(y, face, couponRate, m, ppy)
print(price)