# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7supobcXfATDcweGVZJ3eaM-_o5o1A-
"""

# No Loops! All vectorized code.

import numpy as np

def getBondDuration(y, face, couponRate, m, ppy=1):
  cf = couponRate * face / ppy
  totalPVCF = 0
  totalWeightedPVCF = 0

  years = np.arange(1, m + 1)
  df = 1/(1+y/ppy)
  dfs = df ** years

  pvcf = np.zeros_like(years)
  pvcf[:-1] = cf * dfs[:-1]
  pvcf[-1] = (cf + face) * dfs[-1]

  totalPVCF = np.sum(pvcf)
  totalWeightedPVCF = np.sum(years * pvcf)

  bondDuration = totalWeightedPVCF / totalPVCF
  return(bondDuration)

# Test Value

y = 0.03
face = 2000000
couponRate = 0.04
m = 10
ppy = 1
getBondDuration(y , face , couponRate , m , ppy)