# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7supobcXfATDcweGVZJ3eaM-_o5o1A-
"""

def WhoAmI():
    return 'xl3468'

# Example usage:
print(WhoAmI())